### ISSUE TITLE
Both default and rollover icons on the search button are missing

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-streams#446]
Firefox version: 45.0
Addon version: 1.0.5
OS: Ubuntu 14.04

![screenshot from 2016-04-02 20 06 10](https://cloud.githubusercontent.com/assets/1455254/14229849/a6c7a80e-f90e-11e5-91a8-88b1ba604234.png)

**Comment by pdehaan** [comment]
Ref #443

**Comment by ncloudioj** [comment]
Fixed in #443

**Comment by rlr** [comment]
I think it was broken in #443, not fixed. We no longer have font awesome.

**Comment by ncloudioj** [comment]
Oops, I thought that was already fixed in #443. Reopen it.

**Comment by pdehaan** [comment]
Yeah, we need to revert #443 since it's no longer Apr 1.

**Comment by rlr** [comment]
heh. Was it an April Fools joke? :laughing:

**Comment by rlr** [comment]
FTR: All the icons do show up for me. Well done :clap:

**Comment by ncloudioj** [comment]
It does work on my Mac, but damn I also have a Linux box. NVM, closing this.
