### ISSUE TITLE
Bug 1262169 - Bookmarked website is displayed every time, when "See more activity" button is clicked

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#471]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262169

---

Created attachment 8738150 [details]
bookmarked item.mp4

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.7) was previously installed on a profile.
- Only one website is bookmarked.

#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Click on "Bookmarks" button from Activity Stream sidebar menu.
4. Click on "See more activity" button from Bookmarks screen.

#### [Expected results]:
If the number of bookmarked items doesn't exceed the maximum number of bookmarked items that can be displayed in viewport, "See more activity" button from Bookmarks screen should be hidden.

#### [Actual results]:
The bookmarked website is displayed every time, when "See more activity" button is clicked.

---

This issue is reproducible also in "Just now" area. This issue can be better seen when there are only 4-5 visited websites. When "See more activity" button is clicked, the last item from "Just now" area is displayed for every time the button is clicked.

**Comment by pdehaan** [comment]
Closing. Can you please confirm this is resolved in latest build.

**Comment by softvision-VladBacia** [comment]
This issue was verified on Activity Stream v1.0.14-dev and cannot be reproduced. However, bug 1259396 that was marked as a duplicate to this, is still reproducible. 
In my opinion these two bugs have different scenarios with different expected results and should be handled separately. Thus, I will reopen bug 1259396 (GitHub issue 454).

Please mark this issue as Resolved-Fixed in Bugzilla so I could mark it as Verified-Fixed.
